# -*- coding: utf-8 -*-
"""Day_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p48xZNXyted58XeYZYknY0XP3EMDOKwe
"""

#TODAY TOPICS
# LAMBDA
# MAP
# FILTER

#LAMBDA -->1. A lambda function is a small ananymous function. Anonymous means the function does not have a name .
          #2. Lambda function are useful when a function is needed only once and does not need reused elsewhere

   # Syntax : lambda arguments : expression --> a = lambda x: x ** 2
   #  a= function name
   #  lambda = function keyword
   #  x= argument
   #  ** = expression

   #Interview Definition

#Lambda function is an anonymous, single-expression function defined using the lambda keyword.

square = lambda x:x*x
print(square(5))

tax = lambda x:x*0.03
print(tax(400000))

sum = lambda a,b : a+b
print(sum(16,11))

max = lambda a,b: a if a>b else b
print(max(16,11))

#MAP --> the MAP() function applies the same operation to every item in a collection
# Syntax --> map(function, iterable)

numbers= [1,2,3,4,5]
result= map(lambda x:x *2,numbers)
print(list(result))

# FILTER --> The filter() function selects only the items that satisfy a condition
# Syntax --> filter(function, iterable)

numbers = [1,2,3,4,5,6]
even_numbers = filter(lambda x: x%2==0,numbers)
print(list(even_numbers))

#REDUCE FUNCTION -->Reduce combines all values into a singel value.
                    #It repeatedly performs an action until only one result remains
#IMPORT --> from functools import reduce
#SYNTAX --> reduce(function , iterable)
from functools import reduce
numbers = [1,2,3,4]
result = reduce(lambda x,y:x+y,numbers)
print(result)

#ZIP FUNCTION -->The zip() function combines two or more iterables (lists, tuples, etc.) element by element into pairs (or tuples).
#Syntax --> zip(iterable1,iterable2,...)
names = ["Mukesh", "Rahul", "Kiran"]
marks = [85, 90, 88]

result = list(zip(names, marks))

print(result)

#ENUMERATE FUNCTION --> The enumerate() function automatically adds an index number.

fruits = ["apple", "banana", "mango"]
for index, fruit in enumerate(fruits, start=1):
    print(index, fruit)

#SORTED FUNCTION --> Sort() function sorts the data in ascending or decending order

numbers = [1,3,4,2,7,0]
numbers.sort()
print(numbers)

#ANY FUNCTION --> Prints TRUE if any condition is true
a=30
b=45
numbers = [a>b , a<b]
print(any(numbers))

#ALL FUNCTION -->The all() function returns True only if all elements in an iterable are True

a=45
b=45
numbers = [a>=b,a<=b,a==b]
print(all(numbers))

#NUMPY -- >NumPy is a fundmental package for numerical computing in python. It provides support for dimensional arrays
!pip install NumPy
import numpy as np
import sys
list_1000000=list(range(1000000))
array_1000000=np.arange(1000000)
print(f"size of list: {sys.getsizeof(list_1000000)} bytes")
print(f"size of array: {array_1000000.nbytes} bytes")
import time

#sum the list
start_time= time.time()
sum_list=sum(list_1000000)
end_time=time.time()
list_sum_time = (end_time-start_time) *1000

#sum the array
start_time = time.time()
sum_array = np.sum(array_1000000)
end_time = time.time()
array_sum_time = (end_time-start_time)*1000

print(f"sum of list: {list_sum_time:.2f} milliseconds")
print(f"sum of array: {array_sum_time:.2f} milliseconds")